### ISSUE TITLE
TypeError: ref.save is not a function

### ISSUE THREAD

**Issue by kolaloko** [zappajs/zappajs#125]
I'm getting an error this error after I upgraded zappajs from 5.2.0 to 6.0.2 or higher.
The error occurs after client connection via socket.io. Should I change something before the upgrade?

```
/home/kola/server/node_modules/zappajs/lib/io-session.js:153
           return (ref = ctx.session) != null ? ref.save() : void 0;
                                                    ^

TypeError: ref.save is not a function
    at /home/kola/server/node_modules/zappajs/lib/io-session.js:153:52
    at get_session (/home/kola/server/node_modules/zappajs/lib/io-session.js:126:9)
    at /home/kola/server/node_modules/zappajs/lib/io-session.js:144:14
    at /home/kola/server/node_modules/zappajs/lib/zappa.js:300:18
    at /home/kola/server/node_modules/zappajs/lib/zappa.js:607:20
    at Namespace.<anonymous> (/home/kola/server/node_modules/zappajs/lib/zappa.js:629:50)
    at emitOne (events.js:82:20)
    at Namespace.emit (events.js:169:7)
    at Namespace.emit (/home/kola/server/node_modules/socket.io/lib/namespace.js:209:10)
    at /home/kola/server/node_modules/socket.io/lib/namespace.js:177:14
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

**Comment by shimaore** [comment]
How do you create the session object used by ZappaJS?
And do you register that session object with `@use session: ` ?

**Comment by kolaloko** [comment]
```
ExpressRedisStore = require('connect-redis') @session
@sessionStore = new ExpressRedisStore(
    host: redisUrl.host
    port: redisUrl.port
    pass: redisUrl.password
    db: redisUrl.database
    ttl: ttlTime
)
@use session:
    store: @sessionStore
    maxAge: age
    secret: sessionSecret
    cookie:
        maxAge: age
        secure: true
    resave: true
    saveUninitialized: false
    name: name
```
